export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Tu Ruta en Minutos",
  headline: "Ve en Transmilenio, cómodo y seguro",
  description:
    "Con nuestras predicciones colaborativas, ayudanos a colocarte en el bus correcto",
  buttonLabel: "Inicia Ahora",
  imgStart: false,
  img: require("../../images/bus_stop.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};
export const homeObjTwo = {
  id: "working",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Ante todo: La privacidad",
  headline: "Tus datos, siempre Anónimos",
  description:
    "Tus datos y los datos de los miles de usuarios, nos ayudan a predecir el comportamiento de los buses y del sistema",
  buttonLabel: "Inicia Ahora",
  imgStart: false,
  img: require("../../images/data.svg").default,
  alt: "Car",
  dark: false,
  primary: true,
  darkText: true,
};
export const homeObjThree = {
  id: "planner",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Buses Aprovechados",
  headline: "Llega en menos tiempo a tu destino",
  description: "Qué mejor que ir sentado y en un tiempo menor?",
  buttonLabel: "Inicia Ahora",
  imgStart: false,
  img: require("../../images/bus_stop_2.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};
